Selector
pyansys/pydpf-post pull request #207
Opened 2022-12-08 09:30 UTC by cbellot000

2022-12-08 09:59 UTC, cbellot000 commented on src/ansys/dpf/post/tools.py
> +def select(time_freq_indexes=None, time_freq_sets=None, time_freq_values=None, named_selection_names=None, kwargs=None):
named_selection_name

2022-12-08 09:59 UTC, cbellot000 commented on src/ansys/dpf/post/tools.py
> +    current_selection = selection.Selection()
parse inputs and raise

2022-12-08 09:59 UTC, cbellot000 commented on src/ansys/dpf/post/selection.py
> +
select_body(partid)

2022-12-08 09:59 UTC, cbellot000 commented on src/ansys/dpf/post/selection.py
> +    def select_intersection_with(self, spatial_selection) -> None:
intersect(...)

2022-12-08 11:59 UTC, germa89 requested changes

2022-12-08 11:59 UTC, germa89 commented on src/ansys/dpf/post/selection.py
> +        self._qualifier_selection = None
I think we should be instantiating the object the properties itself. Like

```suggestion
    def __init__(self, time_freq_select=None, nodes=Node, server=None):
        self._server = server
        self._spatial_selection = SpatialSelection(nodes=nodes, server=server)
        self._time_freq_selection = TimeFreqSelection(time_freq_select=time_freq_select, server=server)
        self._qualifier_selection = None
```

2022-12-16 14:54 UTC, PProfizi commented
Closing as changes have been integrated in #208

2022-12-16 14:54 UTC, closed without merging